### ISSUE TITLE
How can auto load schema files?

### ISSUE THREAD

**Issue by TangMonk** [mirego/activerecord_json_validator#23]

**Comment by remiprev** [comment]
@TangMonk I’m not sure I understand your question. Can you explain a little more?

**Comment by TangMonk** [comment]
For example:

```ruby
class User < ActiveRecord::Base
  # Constants
  PROFILE_JSON_SCHEMA = Rails.root.join('config', 'schemas', 'profile.json_schema').to_s

  # Validations
  validates :profile, presence: true, json: { schema: PROFILE_JSON_SCHEMA }
end
```

It will load schema files manually, If there is a way to do following:

```ruby
class User < ActiveRecord::Base

  validates :profile, json: true 
end
```

If specify ```json: true ``` validation, it will auto load schema file named `profile.json` in `config/schemas/user/profile.json` directory.

Directory structure convention:

schema root directory: `config/schemas` (Can configuration)

tables are directories in root directory, json fields in table directory:

```
-config/schemas
----user
------profile.json
```

I think that will better than before

**Comment by remiprev** [comment]
It’s a good idea but I don’t think this is something we want to support in the gem. We prefer our code to be explicit and less _magical_ :smile: 

I’m going to close this issue and the related pull request. Feel free to re-open it if you want to add anything else.

**Comment by TangMonk** [comment]
hi, magical is optional, people can specify path or auth load. "there's more than one way to do one thing", right?
