### ISSUE TITLE
Plans to support active_record 5+?

### ISSUE THREAD

**Issue by biznickman** [mirego/activerecord_json_validator#28]
Right now the gem requires active_record less than 5 which results in errors in the new Rails.

**Comment by remiprev** [comment]
@biznickman Would you be interested in submitting a pull request that would add support for ActiveModel 5+?

**Comment by remiprev** [comment]
Looks like there are already two pull requests that add support for Rails 5. I’ll take a look at them.

**Comment by remiprev** [comment]
Aaaaand it’s done! `activerecord_json_validator-1.1.0` supports Rails 5!
