### ISSUE TITLE
format: "email" support?

### ISSUE THREAD

**Issue by igorescobar** [mirego/activerecord_json_validator#29]
Hello,

Just one question... does this gem support the `format` option like this schema:

```
     "communication_emails": { 
      "type": "array",
      "uniqueItems": true,
      "items": {
      	"type": "string",
        "format": "email"
      }
    }
```

Thank you :)

**Comment by igorescobar** [comment]
It seem to work on: http://www.jsonschemavalidator.net/ but couldn't put this to work using this gem.

**Comment by remiprev** [comment]
This gem doesn’t actually perform any schema validation. Everything is done with the [`json-schema`](https://github.com/ruby-json-schema/json-schema) gem. Can you try and validate your schema with it?

**Comment by igorescobar** [comment]
@remiprev yeah you are right. after reading a few issues on `json-schema` i noticed that they dropped support for it.

**Comment by igorescobar** [comment]
thanks!
