### ISSUE TITLE
Validate entire object with single schema?

### ISSUE THREAD

**Issue by nightscape** [mirego/activerecord_json_validator#30]
Hi all,

I would like to validate an entire object (in our case a `Condition` object having `field`, `operation` and `value`) using a single JSON schema like this:
```ruby
PROFILE_JSON_SCHEMA = {
    type: "object",
    properties: {
      field: { type: "string", enum: ["earnings", "label", "city"] },
      operation: { type: "string", enum: ["greater_than", "equals", "close_to"] },
      value: { type: "string" }
    },
    required: ["field", "operation", "value"]
  }.to_json
```

In the actual JSON schema (which I still have to figure out), the available `operation`s and possible `value`s would depend on the type of the `field`, so `"earnings"` can have a `"greater_than"` operation and `"city"` a `"close_to"` operation.

What I would like to write now is either something like this
```ruby
class Condition < ActiveRecord::Base
  validates :field, json: { schema: PROFILE_JSON_SCHEMA, property: "field" }
  validates :operator, json: { schema: PROFILE_JSON_SCHEMA, property: "operator" }
  validates :value, json: { schema: PROFILE_JSON_SCHEMA, property: "value" }
end
```
or even better
```ruby
class Condition < ActiveRecord::Base
  validates :self, json: { schema: PROFILE_JSON_SCHEMA }
end
```

Is this currently possible?
If not, which version seems better and more feasible to you and would you accept a corresponding PR?

**Comment by nightscape** [comment]
Ah, maybe I can even partially answer myself: The `json-schema` gem has a `fragment` option which can be used to specify against a sub-schema:
```ruby
class Condition < ActiveRecord::Base
  validates :field, json: { schema: PROFILE_JSON_SCHEMA, fragment: "#/properties/field" }
  validates :operator, json: { schema: PROFILE_JSON_SCHEMA, fragment: "#/properties/operator" }
  validates :value, json: { schema: PROFILE_JSON_SCHEMA, fragment: "#/properties/value" }
end
```
Unfortunately that does not work yet because of https://github.com/mirego/activerecord_json_validator/issues/31

**Comment by remiprev** [comment]
I’m going to close this issue since #32 and #33 are now closed.
