### ISSUE TITLE
Cannot validate attributes that are not objects

### ISSUE THREAD

**Issue by nightscape** [mirego/activerecord_json_validator#31]
The following example for validating a non-object field fails because activerecord_json_validator [tries to parse every `String` value as JSON object and defaults to `{}` if this doesn't work](https://github.com/mirego/activerecord_json_validator/blob/master/lib/active_record/json_validator/validator.rb#L37-L44):
```ruby
class Condition < ActiveRecord::Base
  FIELD_SCHEMA = {
    type: "string",
    enum: ["earnings", "label", "city"]
  }.to_json
  validates :field, json: { schema: FIELD_SCHEMA }
  # ...
end
```

This also prevents the usage of the `fragment` option of json-schema in https://github.com/mirego/activerecord_json_validator/issues/30 to validate multiple (String) fields out of a single JSON schema.

**Comment by remiprev** [comment]
> The following example for validating a non-object field fails

Can you actually show an example of how `Condition#field=` fails? What is the argument you’re passing?

**Comment by nightscape** [comment]
I should have been more specific about what happens in that case:
If you assign a new String value to such a string field, the value is replaced by `{}`.
I created a PR that both shows the problem and has a potential solution: https://github.com/mirego/activerecord_json_validator/pull/32

**Comment by remiprev** [comment]
I’m going to close this issue since #32 and #33 are now closed.
