### ISSUE TITLE
Have Abstract Base Class Call Method to determine schema location

### ISSUE THREAD

**Issue by amaxsurge** [mirego/activerecord_json_validator#40]
This is more of a support request than a bug but I'm hoping maybe it will be obvious to someone familiar with the project.

I might just be running up against my understanding of how Ruby Classes and Modules work but I cannot figure out how to get a class to call a method when determining the `json_schema` path.

I have a base class that is trying to delegate out the schema path to its child classes so they can interpolate their own name into the path to identify their schema file.

```Ruby
class StateChangeModule < ActiveRecord::Base
  has_and_belongs_to_many :data_generating_modules

  validates :module_data, presence: true, json:  { message: ->(errors) { errors },  schema: json_schema_path }

  def json_schema_path
    "#{Rails.root}/app/json_schemas/state_change/#{self.class.name.underscore}.json"
  end
end
```

So I would then have a class `NewModule < StateChangeModule` and I'd have a schema file at `app/json_schemas/state_change/new_module.json`

But when I try to load this class, the `validates` method can't find `json_schema_path` and fails with: `NameError (undefined local variable or method 'json_schema_path' for #<Class:0x00007f44ac1c5a28>)`

I have about 50 of these StateChangeModules(which is a class, not a module, confusing I know) so I really don't want to do this 50 times.

Any thoughts on how I could get this working?

**Comment by amaxsurge** [comment]
@remi @willsoto any thoughts?  still can't get this to work

**Comment by remi** [comment]
Hi! Sorry, I completely forgot about this.

So, in the following:

```ruby
validates :module_data, presence: true, json:  { message: ->(errors) { errors },  schema: json_schema_path }
```

The `json_schema_path` is evaluated as class method, and there is no `json_schemna_path` method.

The [`schema` option](https://github.com/mirego/activerecord_json_validator#schema) supports various types — one of them is a lambda which is executed in the context of your record. So this would work:

```ruby
validates :module_data, presence: true, json:  { message: ->(errors) { errors },  schema: lambda { json_schema_path } }
```

This will work too:

```ruby
validates :module_data, presence: true, json:  { message: ->(errors) { errors },  schema: :json_schema_path }
```

Hope this helps!

**Comment by amaxsurge** [comment]
Thanks so much @remi !  Really enjoying using this gem.

**Comment by Andrew-Max** [comment]
@remi, your answer has helped me make really good progress on my app and may allow me to publish a further gem based off of this. Would you be open to a pr to update some documentation? Also would you have any interest in taking a look in this other project? It essentially allows an STI setup where all of the sub type data lives in a json blob and still has validations via your gem. It seems super powerful and simple from my use of it so far.

**Comment by remi** [comment]
> Would you be open to a pr to update some documentation?

Yes, sure!

> Also would you have any interest in taking a look in this other project?

I’ll happily take a look. But keep in mind that we’re no longer using Ruby as our main programming langage at Mirego so my expertise is a little outdated 😄
