### ISSUE TITLE
Can't set rule for array of hashes

### ISSUE THREAD

**Issue by spazer5** [mirego/activerecord_json_validator#41]
```
class PropsContract < Dry::Validation::Contract
  json do
    required(:contacts).value(:array, min_size?: 1).each do
      hash do
        required(:name).filled(:string)
        required(:email).filled(:string)
        required(:phone).filled(:string)
      end
    end
  end

  rule("contacts.email").validate(:email_format)
end
```

This errors out: `Dry::Validation::InvalidKeysError: PropsContract.rule specifies keys that are not defined by the schema: ["contacts.email"]`

**Comment by remi** [comment]
Hi @spazer5,

I’m not sure what the link with `ActiveRecord::JSONValidator` is here. Can you provide more information?

Thank you!

**Comment by spazer5** [comment]
Sorry! Posted on the wrong repo 😊
