### ISSUE TITLE
Allow type or null

### ISSUE THREAD

**Issue by Andrew-Max** [mirego/activerecord_json_validator#42]
I have a schema: 
```
{
    type: "object",
    properties: {
      product_id:      { type: "string" },
      tip_description: { type: "string" },
      core_diameter:   { type: "number" },
      outer_diameter:  { type: "number" },
      aperature:       { type: "number" },
    },
    required: []
  }
```

Note nothing is required here and the only way to set an `undefined` is with `null`

So it seems to me like this should be a valid entry

```
{
  "product_id": null,
  "tip_description": null,
  "core_diameter": null,
  "outer_diameter": null,
  "aperature": null
}
```
But validation fails telling me that it expected string or numeric types, not null. I explicitly do not want to trim out null properties, I want them to be saved as present with a value of `null` so it is clear to end users which properties exist.

Is there any way to accomplish this?

**Comment by remi** [comment]
Hi Andrew,

This looks like a problem related to the [`json-schema`](https://rubygems.org/gems/json-schema) gem. Are you able to reproduce the validation bug using just the gem (and not through `activerecord_json_validator`)?

Hope this helps!

**Comment by Andrew-Max** [comment]
Yeah, makes sense, I'll open it up over there.

**Comment by JoeyBG** [comment]
Hey Andrew,

There is actually a problem with your schema. To allow explicit nulls in your JSON, you would need to declare your schema in the following manner:

```
{
    type: "object",
    properties: {
      product_id:      { "type": ["string", "null"] },
      tip_description: { "type": ["string", "null"] },
      core_diameter:   { "type": ["number", "null"] },
      outer_diameter:  { "type": ["number", "null"] },
      aperature:       { "type": ["number", "null"] },
    },
    required: []
  }
```

You can read more about this [here](https://stackoverflow.com/questions/16241333/specify-a-value-can-be-a-string-or-null-with-json-schema) or in the official documentation.

In short, `required` validates if the key is present in the JSON object, and `type` validates if the type is correct. `null` is neither a string or a number, so the validation fails.
