### ISSUE TITLE
No validation error if invalid key

### ISSUE THREAD

**Issue by ParthivSavani** [mirego/activerecord_json_validator#44]
Hello,

I'm trying to create/update the the JSON with wrong key but it's getting updated without trigger any error. It should be rollback and trigger the validation error.

Schema
```
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "properties": {
    "user": {
      "type": "object",
      "properties": {
        "sticker": { "type": "boolean" },
        "zakat": { "type": "boolean" },
        "inventory": { "type": "boolean" },
        "credit": {
          "type": "object",
          "properties": {
            "order": { "type": "integer" },
            "shown": { "type": "boolean" }
          },
          "required": ["order", "shown"]
        },
        "transactions": {
          "type": "object",
          "properties": {
            "order": { "type": "integer" },
            "shown": { "type": "boolean" }
          },
          "required": ["order", "shown"]
        }
      }
    }
  }
}
```

JSON
```
preferences: {"user"=>{"transactions"=>{"shown"=>true, "order"=>2}, "credit"=>{"shown"=>true, "order"=>1}, "zakat"=>false, "**wrongkey**"=>true}}
```

I changed key from **sticker to wrongkey** and save. It was updated without any error.

**Comment by jfcartkeep** [comment]
Hi,

You need to use the `additionalProperties` with `false` (documentation [here](https://json-schema.org/understanding-json-schema/reference/object.html#id2)) in your JSON schema to have an error on properties not defined in your schema.

With `additionalProperties` to `false`, any properties whose names are not listed in the schema will produce an error.

**Comment by ParthivSavani** [comment]
@jfcartkeep It works. Thanks!

**Comment by ParthivSavani** [comment]
@jfcartkeep Sorry had one question, as you can see in my schema there are multiple properties. So, do I need to add `,
  "additionalProperties": false` for all individual properties or we can add one for all? How?

**Comment by jfcartkeep** [comment]
> Sorry had one question, as you can see in my schema there are multiple nested properties. So, do I need to add `"additionalProperties": false` for all individual properties or we can add one for all? How?

As far as I know, you need to add `additionalProperties` on each nested object.
