### ISSUE TITLE
Move to using json_schemer gem for newer specifications

### ISSUE THREAD

**Issue by ttanay** [mirego/activerecord_json_validator#45]
The [`json-schema`](https://github.com/ruby-json-schema/json-schema/) ruby gem doesn't newer specifications of the JSON schema, specifically draft 7 that I want to use. [Draft 7 has useful features](https://json-schema.org/draft-07/json-schema-release-notes.html) that I'd like to use along with this gem, but, it's not possible due to the JSON schema validation gem that this uses. 
Also, looks like the [`json-schema` gem is not being maintained](https://github.com/ruby-json-schema/json-schema/issues/423). 
Is it possible to switch to another gem like [`json_schemer`](https://github.com/davishmcclurg/json_schemer) that supports newer specifications?  

Happy to take up the change if you decide to go ahead with it.

**Comment by amygurski** [comment]
I don't know if there is interest in this, but we ran into this issue as well - our app recently started using draft 6 (previously it was just draft 4) and it broke. I started work on a PR just in case there is interest in moving forward with your lovely suggestion @ttanay : https://github.com/mirego/activerecord_json_validator/pull/46

**Comment by remi** [comment]
I merged #46 and released [activerecord_json_validator-2.0.0](https://rubygems.org/gems/activerecord_json_validator/versions/2.0.0)! 🎉 

Thanks again Amy!
