### ISSUE TITLE
Does this work with postgres JSONB data types?

### ISSUE THREAD

**Issue by nratter** [mirego/activerecord_json_validator#47]
We're using the JSONB data type on Postgres. I've set this up for a particular JSONB field, and I keep getting the error `JSON::ParserError: 783: unexpected token at 'var/app/config/schemas/organization_meta.json_schema'` when testing validation using this gem. I even tested the schema using the exact schema in the README.

Any ideas?
Does this work with JSONB data types?

**Comment by remi** [comment]
Hi Nick,

How are you declaring the validation in your model? From your error message, it looks like the code is trying to use some kind of file path (`'var/app/config/schemas/organization_meta.json_schema'`) as JSON data.

I think it might be how the new `json_schemer` gem [works](https://github.com/davishmcclurg/json_schemer/blob/master/lib/json_schemer.rb#L53-L64). It treats any string as a JSON string and you have to use a `Pathname` if you want to treat it as a file path.

If that’s the issue, can you try it again with a `Pathname`? I think we’ll just need to update the `README`.

**Comment by nratter** [comment]
Yep this was the issue! I'll try and submit a pull request tomorrow to fix the README up. Thanks!

**Comment by remi** [comment]
I believe this was closed by #49 👍
