### ISSUE TITLE
Issue with error messages after 2.0.0 release

### ISSUE THREAD

**Issue by mhfs** [mirego/activerecord_json_validator#48]
Prior to 2.0.0 a schema failure in a model would result in something like this:

```
model_instance.errors.full_messages
"Data The property '#/something/Status' value \"Wrong\" did not match the regex '^(Closed|Open)$' in schema file:///Users/.....json"
```

Now it returns this:

```
["Data {\"data\"=>\"Wrong\", \"data_pointer\"=>\"/something/Status\", \"schema\"=>{\"type\"=>\"string\", \"pattern\"=>\"^(Closed|On Hold)$\"}...
```

Was that expected? Regression?

**Comment by remi** [comment]
This is most likely related to the switch from `json-schema` to `json_schemer` (#46). The validator just takes the error from `json_schemer` and add it to the instance errors.

I’m guessing you’re using something like this for the `message` option:

```ruby
message: ->(errors) { errors }
```

This is where you could do some processing to build a more human-friendly message like the one `json-schema` previously provided.

Hope this helps!

**Comment by mhfs** [comment]
Thanks @remi.
