### ISSUE TITLE
Use in a library?

### ISSUE THREAD

**Issue by kjanoudi** [mirego/activerecord_json_validator#59]
Hello, we use the 1.x version of this gem in a library, and are looking to upgrade to rails 7. With 2.x, it looks like we're forced to move our schemas into external files. Is there a workaround for this that maintains compatibility with passing a string for the schema, or do you have any tips on using this with a library where the schema files would not always be in the same spot?

**Comment by remi** [comment]
Hi Kareem,

> it looks like we're forced to move our schemas into external files

Fortunately, no you’re not! 🙂 

We’re passing the schema directly to [`JSONSchema.schema`](https://github.com/davishmcclurg/json_schemer/blob/bbfed4ccdcab85c540568effefcbef308c5bb6a4/lib/json_schemer.rb#L53-L69) function. Take a look at [JSONSchemer](https://github.com/davishmcclurg/json_schemer) documentation:

```ruby
# schema files

require 'pathname'

schema = Pathname.new('/path/to/schema.json')
schemer = JSONSchemer.schema(schema)

# schema json string

schema = '{ "type": "integer" }'
schemer = JSONSchemer.schema(schema)
```

It supports pathnames (paths to external files) and string (serialized schemas). So you can actually use serialized JSON schemas and keep away from external files! 🙌 

Our `README.md` could be clearer though, I’ll add something 👍

**Comment by remi** [comment]
And you can also use a regular Hash to represent the schema:

```ruby
schema = {
  'type' => 'object',
  'properties' => {
    'abc' => {
      'type' => 'integer',
      'minimum' => 11
    }
  }
}
```
