### ISSUE TITLE
Support overridden getters

### ISSUE THREAD

**Issue by kyrofa** [mirego/activerecord_json_validator#62]
I'm trying to integrate this validator into a architecture that uses json columns as rich references to other objects in the database. It overrides the Rails-provided getters with ones that lookup the references and returns the actual Ruby objects instead of the hash. As a result, this validator actually ends up trying to validate a Ruby object against a json schema instead of the hash that's actually in the database. In other validators we handle this by ignoring the value provided by `validate_each` and accessing the attribute directly. So instead of doing this:

```
def validate_each(record, attribute, value)
  errors = do_my_validation(value)
  return if errors.empty?
  # ...
end
```

We do this:

```
def validate_each(record, attribute, _value)
  errors = do_my_validation(record[attribute])
  return if errors.empty?
  # ...
end
```

Admittedly I don't love this solution, but it works. Is there a way to support this architecture in this validator?

Right now I'm simply customizing in a subclass, which is workable:

```
class MyJsonValidator < ::JsonValidator
  def validate_each(record, attribute, _value)
    super(record, attribute, record[attribute])
  end
end
```

**Comment by kyrofa** [comment]
Makes perfect sense, thank you!

**Comment by remi** [comment]
@kyrofa I just cut a new release. v2.1.2 should work as expected now, without having to use your custom `MyJsonValidator` 🎉
