### ISSUE TITLE
Support overridden setters

### ISSUE THREAD

**Issue by kyrofa** [mirego/activerecord_json_validator#66]
Me again, from the very-similar #62 :stuck_out_tongue: .

We've been using v2.1.3 in prod for a while, but recently noticed some odd issues, and finally traced it back to the fact that this validator actually overrides the model setter.

Backing up to provide some history: this is the same codebase as in #62. Not only does it override the Rails-provided getters to lookup references and return Ruby objects, it inversely overrides the Rails-provided setters: accept an object and turn it into a rich reference.

A fair amount of our code actually hands it pre-formed rich references anyway so we didn't notice the issue until we actually tried to hand it a model, and it didn't work the way we expect where we have this validator configured because the actual setter that is called isn't ours, it's [yours](https://github.com/mirego/activerecord_json_validator/blob/0af34f5e27c2b36a4501018581520c2b9742bf25/lib/active_record/json_validator/validator.rb#L43).

The comment you have there is helpful: I believe you are redefining the setter so that you can catch invalid json before the validation runs, but I'm not entirely clear why you don't just lean on the validation for that. It would catch invalid json, right? Could it be enhanced to write the `#{attribute}_invalid_json` attribute? i.e. is this setter even necessary? If it is, perhaps it should be done in a module added to the ancestry instead of patching the class itself.

**Comment by aramgre** [comment]
Unfortunately, the fix in #71 breaks the following code (prepending the injected setter bypasses our setter before the input can be coerced):

```rb
validates :foo, json: { schema: SCHEMA }

def foo=(value)
  super(value.is_a?(String) ? YAML.safe_load(value) : value)
end
```

Ideally there might be a solution that doesn't inject accessors into the model. `ActiveModel::Validations` doesn't actually require accessors to even be defined, so for example this code will never invoke the injected setter:

```rb
class User
  include ActiveModel::Validations

  validates :profile, json: { schema: PROFILE_JSON_SCHEMA }

  def initialize(data)
    @data = data
  end

  # override method for passing attributes to the validator
  # https://github.com/rails/rails/blob/main/activemodel/lib/active_model/validations.rb#L415
  def read_attribute_for_validation(key)
    @data[key]
  end
end
```

**Comment by kyrofa** [comment]
> Unfortunately, the fix in https://github.com/mirego/activerecord_json_validator/pull/71 breaks the following code (prepending the injected setter bypasses our setter before the input can be coerced):

Oh no! Sorry for the breakage. How did this work for you in the past? The validator completely overwrote your `foo=` setter, no?

**Comment by aramgre** [comment]
@kyrofa with activerecord_json_validator 2.1.1, it looks like our code was overwriting the injected setter because our setter was declared later than the call to `validates`:
```rb
validates :foo, json: { schema: SCHEMA } 

def foo=(value)
  puts "our code"
  super(value.is_a?(String) ? YAML.safe_load(value) : value)
end
```

if the order is reversed, I can confirm that the validator does completely overwrite our code: 

```rb
def foo=(value)
  puts "our code" # never gets called
  super(value.is_a?(String) ? YAML.safe_load(value) : value)
end

validates :foo, json: { schema: SCHEMA }
```

with the change in #71, the injected setter always gets called first, then calls super which is our setter, but by then the [injected setter has already modified the input](https://github.com/mirego/activerecord_json_validator/blob/v2.1.5/lib/active_record/json_validator/validator.rb#L49C13-L49C17).

**Comment by kyrofa** [comment]
So it really sounds like this is broken either way. This will require some thought.
