### ISSUE TITLE
Include schema errors as an attribute on error message

### ISSUE THREAD

**Issue by lcmen** [mirego/activerecord_json_validator#68]
Hello Mirego guys!
Thanks for this gem. It provides ton of help to deal with validation JSON object. Unfortunately when working with more complex schemas, it's a bit daunting to find which part of json value invalidates the schema - default error message (picked by `I18n.t`) is not able to include schemer details.

So far I've overcome this issue by overriding part responsible for adding errors inside `validate_each` method on validator:

```ruby
message(errors).each_with_index do |message, index|
  error = errors[index]
  error = JSONSchemer::Errors.pretty(error) if error.is_a?(Hash)
  record.errors.add(attribute, message, error:, value:)
end
```

Thanks to this change, I can include error details using `error` key in the translated error message (e.g. `Invalid JSON ({error})`).

Would like to have it as a default behavior? If so, I'm more than happy to prepare PR.

**Comment by remi** [comment]
Hi Lucas! 👋 

That makes sense! I’m guessing it would be backward compatible (ie. no bad side effect if the `{{error}}` key is not present in the localized error message), correct?

**Comment by lcmen** [comment]
> That makes sense! I’m guessing it would be backward compatible (ie. no bad side effect if the `{{error}}` key is not present in the localized error message), correct?

Yes, it's backward compatible as `error` is an option on `ActiveModel::Error` object (the same way as `value` is an option there). If this field is not used in the error message then nothing will happen, it will simply be ignored.

In this case I will prepare a PR to add this feature. Thanks!

**Comment by remi** [comment]
Awesome, I’ll wait for the PR then. Thank you for contributing! And thank you for opening an issue beforehand, that’s always a good practice 😁.

**Comment by remi** [comment]
@lcmen v2.1.4 was released with the new `errors` option. Thanks again!

**Comment by lcmen** [comment]
Awesome, thank you @remi !
