### ISSUE TITLE
Support JSONSchemer 2.0

### ISSUE THREAD

**Issue by ekzobrain** [mirego/activerecord_json_validator#73]
New major version of https://github.com/davishmcclurg/json_schemer has been released featuring support for all actual JSON Schema versions.

**Comment by davishmcclurg** [comment]
Just opened a PR for upgrading to 2.0: https://github.com/mirego/activerecord_json_validator/pull/78

**Comment by bengolder** [comment]
Hey look the `json-schemer` author added a PR! I'm particularly excited about using these two things immediately after it gets merged:
- translation of the json schema validation errors
- validating the schemas themselves

**Comment by remi** [comment]
Sorry guys, I totally forgot about this 😩 

I’ll merge it and release a new major version! 🙌

**Comment by remi** [comment]
Closed with #78
